- name: create a VPC
  ec2_vpc_net: 
    aws_access_key:
    aws_secret_key:
    region: "{ aws_region }"
    name: "{ project_name }"
    cidr_block: 10.0.0.0/16
    tags:
        module: ec2_vpc_net
        tenancy: default
  register: ansibleVPC
  
- name: Display the ansibleVPC output
  debug:
    var: ansibleVPC
    