- name: create a VPC
  ec2_vpc_net: 
    aws_access_key: "{{ aws_id }} "
    aws_secret_key: "{{ aws_key }}"
    region: "{{ aws_region }}"
    name: "{{ project_name }}"
    cidr_block: 10.0.0.0/16
    tags:
        module: ec2_vpc_net
        tenancy: default
  register: ansible_VPC_net
  
- name: Display the ansibleVPC output
  debug:
    var: ansible_VPC_net
    